### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mp1pro** [marstonmd/jammming#3]
Great job. The app works as it should. Did not detect any major errors. I would suggest looking more into the use of states during the lifecycle of the app. Here are a couple great links on states;
https://reactjs.org/docs/state-and-lifecycle.html
and 
https://facebook.github.io/react-vr/docs/components-props-and-state.html

**Comment by marstonmd** [comment]
Thanks for the suggestion and links. I'm on the hunt for more resources to clean up my coding practices early and better use the tools available to me, so these resources should help.
